Image view
mkobuolys/flutter-design-patterns pull request #54
Opened 2023-05-29 13:42 UTC by Juliotati

Updated the code in the original closed PR #24 

Reason for removing the `canLaunchUrl` check

![Screenshot 2023-05-29 at 14 41 47](https://github.com/mkobuolys/flutter-design-patterns/assets/59662912/6745671c-f5a6-4394-a730-b9fa9f34fcfc)

2023-05-29 13:49 UTC, Juliotati commented
wrong commit message there, meant to say:
- image view from #24

2023-05-29 14:53 UTC, mkobuolys commented
> @mkobuolys wrong commit message there, meant to say:
> 
> * image view from [Add better image view #24](https://github.com/mkobuolys/flutter-design-patterns/pull/24)
> 
> Although it bring a good point, that the app could be put in the process for publishing now? I guess the only thing left is:
> 
> * App icon
> * and double check on the `packageId` and display name

Honestly, I don't think that this is a good point. To me, the app is not worth publishing as it is now. At the moment, Flutter Design Patterns is just a lightweight library of design pattern examples implemented in Dart and... that's it?

Here is my take on this project:
1) There is a dedicated domain https://www.flutterdesignpatterns.com where this app is deployed on each code change in the main branch. I would rather keep it this way than semi-automate the release process to the stores.
2) To expand on the point mentioned in the issue about offline learning: I would rather spend some time preparing the app as a fully offline-first PWA application than build an Android/iOS app.

Having these points in mind, I think about removing ios/android directories from the project and focusing on the web version. Also, reducing the maintenance overhead (basically, what you did with this PR by updating the Android project).

2023-05-29 17:07 UTC, Juliotati commented
@mkobuolys I agree seems reasonable, I mainly use the web for everything, and i would use the PWA if i ever need to check on something when can't access the app through a desktop.

2023-05-29 21:55 UTC, mkobuolys commented
Anyway, platform-specific changes are out of scope for this issue/PR, I would like to take a look at them myself or even remove the platforms as mentioned above. Please, revert the changes and only leave Dart code changes to proceed with the review.

2023-05-30 17:48 UTC, Juliotati reviewed
@mkobuolys  done ✨

2023-06-03 16:41 UTC, mkobuolys commented on lib/modules/design_pattern_details/widgets/rich_markdown_body.dart
> +      imageBuilder: (uri, _, __) {
Convert this to expression body (arrow function).

2023-06-03 16:42 UTC, mkobuolys commented on lib/widgets/image_view.dart
> +import 'package:flutter/material.dart';
Import sorting is wrong.

2023-06-03 16:42 UTC, mkobuolys commented on lib/widgets/image_view.dart
> +  Offset _tapPosition = Offset.zero;
Add an empty line before this.

2023-06-03 16:43 UTC, mkobuolys commented on lib/widgets/image_view.dart
> +    }
```suggestion
    if (_controllerReset.isAnimating) return;
    
      _animationReset?.removeListener(_onAnimateReset);
      _animationReset = null;
      _controllerReset.reset();
```

2023-06-03 16:45 UTC, mkobuolys commented on lib/widgets/image_view.dart
> +  }
```suggestion
  void _onDoubleTap() => isInitial ? _animateScaleIn() : _animateScaleOut();
```

2023-06-03 16:46 UTC, mkobuolys commented on lib/widgets/image_view.dart
> +    if (_tapPosition != Offset.zero &&
If case body is empty - invert the condition to avoid this.

2023-06-03 16:47 UTC, mkobuolys commented on lib/widgets/image_view.dart
> +    Timer(const Duration(milliseconds: 500), () {
Add space before this.

2023-06-03 16:47 UTC, mkobuolys commented on lib/widgets/image_view.dart
> +    _animateResetInitialize(
Add space before this.

2023-06-03 16:48 UTC, mkobuolys commented on lib/widgets/image_view.dart
> +    );
```suggestion
    final size = MediaQuery.of(context).size;
    final offset = Offset(-size.width / 4, -size.height / 4);
```

2023-06-03 16:48 UTC, mkobuolys commented on lib/widgets/image_view.dart
> +  void _animateResetStop() {
The code seems like a duplicate of `_onAnimateReset` - extract similar logic to a dedicated function and reuse it.

2023-06-03 16:50 UTC, mkobuolys commented on lib/widgets/image_view.dart
> +    }
```suggestion
    if (_controllerReset.status != AnimationStatus.forward) return;
    
    _animateResetStop();    
```

2023-06-03 16:51 UTC, mkobuolys commented on lib/widgets/image_view.dart
> +        leading: const PlatformBackButton(color: Colors.black),
I don't think that the PlatformBackButton is the right one to use there. I would prefer to have a "X" button on the top right.

2023-06-03 16:54 UTC, mkobuolys requested changes
My initial feeling is that the `ImageView` is a bit overengineered and not everything that's implemented there is needed. Anyway, let's refactor the code a bit for better readability, I will dive a bit deeper with the other iteration.

2023-06-03 17:04 UTC, Juliotati commented
> My initial feeling is that the `ImageView` is a bit overengineered and not everything that's implemented there is needed. Anyway, let's refactor the code a bit for better readability, I will dive a bit deeper with the other iteration.

Considering the code age it's most likely that that's the case

2023-06-09 20:37 UTC, merged